# $HOME/.config/alacritty/alacritty.toml

[general]
import = [
        "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
	      # "~/.config/alacritty/themes/themes/alabaster_dark.toml"
        # "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
]

###### Janela ######
[window]
decorations = "None"
opacity = 0.9
blur = true

###### Fontes ######
[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

###### Cursor ######
[cursor.style]
shape = "Block"
blinking = "On"

###### Comportamentos ######
[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

###### Shell ######
[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

###### Atalhos do teclado ######
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"
